### ISSUE TITLE
关于science advance:A general temperature-guided language model to design proteins of enhanced stability and activity

### ISSUE THREAD

**Issue by xtanh** [ginnm/ThermoFormer#1]
老哥，我想问下stability oracle 你们是怎么复现的呀？因为他的github代码仓库里没有给提取特征的方式，想问下你们是怎么复现的，麻烦了。

**Comment by ginnm** [comment]
您好，我们根据文章思路自己复刻了StabilityOracle。 我建议不要浪费时间在StabilityOracle的代码库上，他们的代码完全没法用在新蛋白上。

**Comment by xtanh** [comment]
老哥，能加您个微信吗。我是上海交通大学熊毅老师课题组的学生。跟你学习请教

**Comment by ginnm** [comment]
可以的 你给我邮箱发一封邮件吧

**Comment by xtanh** [comment]
老哥，已发。
